### ISSUE TITLE
Error when schema.options.type array is empty

### ISSUE THREAD

**Issue by ptrin** [arqo123/speedgoose#68]
While adding speedgoose to my project, I came across an error in `getReferenceModelNameFromSchema` which seems to be caused by arrays of a Mixed type:
```
    TypeError: Cannot read properties of undefined (reading 'ref')

      17 |     }
      18 |     if (Array.isArray(schema?.options?.type)) {
    > 19 |         return schema?.options?.type[0].ref;
         |                                         ^
      20 |     }
      21 | };
      22 |

      at getReferenceModelNameFromSchema (src/utils/hydrationUtils.ts:19:41)
      at Object.<anonymous> (test/utils/hydrateUtils.test.ts:11:47)
```

It's caused by a SchemaType which looks like this:
```
      SchemaArray {
        schemaOptions: {
          typeKey: 'type',
          id: true,
          _id: true,
          validateModifiedOnly: false,
          validateBeforeSave: true,
          read: null,
          shardKey: null,
          discriminatorKey: '__t',
          autoIndex: null,
          minimize: true,
          optimisticConcurrency: false,
          versionKey: '__v',
          capped: false,
          bufferCommands: true,
          strictQuery: false,
          strict: true
        },
        casterConstructor: [Function: Mixed] {
          schemaName: 'Mixed',
          defaultOptions: {},
          get: [Function (anonymous)],
          set: [Function: set],
          setters: []
        },
        caster: Mixed {
          path: 'emptyTypeArray',
          instance: 'Mixed',
          validators: [],
          getters: [],
          setters: [],
          _presplitPath: [ 'emptyTypeArray' ],
          options: SchemaTypeOptions {},
          _index: null,
          _arrayPath: 'emptyTypeArray.$',
          _arrayParentPath: 'emptyTypeArray',
          [Symbol(mongoose#schemaType)]: true,
          [Symbol(mongoose:schema_mixed)]: true
        },
        '$embeddedSchemaType': Mixed {
          path: 'emptyTypeArray',
          instance: 'Mixed',
          validators: [],
          getters: [],
          setters: [],
          _presplitPath: [ 'emptyTypeArray' ],
          options: SchemaTypeOptions {},
          _index: null,
          _arrayPath: 'emptyTypeArray.$',
          _arrayParentPath: 'emptyTypeArray',
          [Symbol(mongoose#schemaType)]: true,
          [Symbol(mongoose:schema_mixed)]: true
        },
        '$isMongooseArray': true,
        path: 'emptyTypeArray',
        instance: 'Array',
        validators: [],
        getters: [],
        setters: [],
        _presplitPath: [ 'emptyTypeArray' ],
        options: SchemaArrayOptions { type: [] },
        _index: null,
        defaultValue: [Function: defaultFn] { '$runBeforeSetters': true },
        [Symbol(mongoose#schemaType)]: true
      }
```

You can reproduce with a Schema like so: `new Schema({ emptyTypeArray: [] })`

I have a PR in progress with a "fix" or at least it will prevent the error, but I don't know if there are any nasty side effects if `getReferenceModelNameFromSchema` returns undefined.

**Comment by arqo123** [comment]
Merged and published as 2.0.8.
Thank You for contributing <3
