### ISSUE TITLE
isCached issue

### ISSUE THREAD

**Issue by x00ibro** [arqo123/speedgoose#73]
I'm using this to cache my results data and console log (isCached)
![image](https://github.com/arqo123/speedgoose/assets/136867770/49374a8d-49e0-4263-b015-a40021d84b51)

However, I keep getting this error:
Error fetching results: TypeError: aggregation.pipeline is not a function
    at generateCacheKeyFromPipeline (test\node_modules\speedgoose\lib\src\utils\cacheKeyUtils.js:15:27)
    at prepareAggregateOperationParams (test\node_modules\speedgoose\lib\src\utils\queryUtils.js:47:180)
    at mongoose.Query.isCached (test\node_modules\speedgoose\lib\src\extendAggregate.js:12:58)
    at test\server.js:608:48
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Any ideas?

**Comment by arqo123** [comment]
Thanks for this finding. 
Fixed in https://github.com/arqo123/speedgoose/pull/74
New version 2.0.9
